var i18n =
{
"Minimum": "Required minimum ",
"Maximum": "Possible maximum",
"one_letter": "letter",
"some_letter1": "letters",
"some_letter2": "letters",
"current_length": "Current length is",
"wrong_value_format": "Wrong value format.",
"different_fields_value": "The fields value are different",
"lock_message": "Form changed! Are you sure you want to leave page without saving?",
"change_image": "Change image",
"save": "Save",
"confirm_delete": "Are you sure you want to delete?",
"remove_event": "Remove event?",
"yes": "Yes",
"no": "No",
"day": " d",
"hour": " h",
"minute": " m",
"ban_success": "IP address blocked!",
"ban_error": "IP address already blocked!",
"important": "important",
"webauth_register_success": "Authorization saved successfully",
"copy_error_clipboard": "Copy error to clipboard"
};